services:
  frontend:
    build:
      context: ./frontend  # or your React app folder
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      
      # Leave this uncommented for online deployment AWS deployed instance ip connects here
      # - REACT_APP_API_BASE_URL=http://3.82.138.12:4000
      
      # Leave this uncommeneted for local deployment localhost:xxxx frontend will connect here
      - REACT_APP_API_BASE_URL=http://localhost:4000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    build:
      context: ./ecommAPI  #backend folder
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    volumes:
      - ./ecommAPI:/app
      - /app/node_modules
    command: ["node", "server.js"] 

